# Generated by Django 4.2.1 on 2023-06-04 17:32

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=djrichtextfield.models.RichTextField(),
        ),
    ]
