# Generated by Django 4.1.7 on 2023-07-13 17:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationDataCommitteeDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nama_panitia', models.CharField(max_length=200, null=True)),
                ('tanggal_tinjau', models.DateField(null=True)),
                ('berkas_lengkap', models.BooleanField(null=True)),
                ('hasil_tinjauan', models.TextField(null=True)),
                ('status_lulus', models.BooleanField(null=True)),
                ('registration_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_seleksi', to='hiring.registrationdata')),
            ],
        ),
    ]
