# Generated by Django 4.1.7 on 2023-07-14 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0002_registrationdatacommitteedecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationdata',
            name='tautan_dokumen_drive_ppsn',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='ekstrakurikuler',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='fakultas',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='instagram',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='jenis_kelamin',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='kota_institusi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='kota_pribadi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='kota_sekolah',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='line',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='linkedin',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='motivasi_bergabung',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='nama_institusi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='nama_lengkap',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='nama_sekolah',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='notelp',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='penjurusan',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='prodi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='prov_institusi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='prov_pribadi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='prov_sekolah',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='semester_sma',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='sistem_sekolah',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tautan_dokumen',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='telegram',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tempat_lahir',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tujuan_bergabung',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='ukm',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='whatsapp',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='keterangan_tambahan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='lembaga_penyelenggara',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='nama_acara',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='tingkat',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='harapan_kontribusi',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='minat_bakat',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='nama_formasi',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='pengalaman',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='tingkat_jabatan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='keterangan_tambahan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='lembaga_penyelenggara',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='masa_kerja_akhir',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='masa_kerja_mulai',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='nama_kegiatan',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='bahasa',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='keterampilan_bicara',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='keterampilan_membaca',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='keterampilan_menulis',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='skor_kemahiran',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdataorganization',
            name='deskripsi_jabatan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdataorganization',
            name='nama_institusi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdataorganization',
            name='posisi_jabatan',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='deskripsi_tambahan',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='jenis_publikasi',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='judul_publikasi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='lembaga_publikasi',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='jenjang',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='lembaga_penyelenggara',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='nama_beasiswa',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='tipe_pendanaan',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='registrationdataskill',
            name='saintek',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdataskill',
            name='sastra',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdataskill',
            name='seni',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registrationdataskill',
            name='sosial',
            field=models.TextField(default=''),
        ),
    ]
