# Generated by Django 4.1.7 on 2023-07-14 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0003_registrationdata_tautan_dokumen_drive_ppsn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='ekstrakurikuler',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='error_notes',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='fakultas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='foto-peserta/'),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='jenis_kelamin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='kota_institusi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='kota_pribadi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='kota_sekolah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='line',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='motivasi_bergabung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='nama_institusi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='nama_lengkap',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='nama_sekolah',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='notelp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='penjurusan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='prodi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='prov_institusi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='prov_pribadi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='prov_sekolah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='semester_sma',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='sistem_sekolah',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tahun_masuk_dikti',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tahun_masuk_sma',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tanggal_lahir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tautan_dokumen',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tautan_dokumen_drive_ppsn',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='telegram',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tempat_lahir',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tujuan_bergabung',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='ukm',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='keterangan_tambahan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='lembaga_penyelenggara',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='nama_acara',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='tahun_perolehan',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataachievement',
            name='tingkat',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatacommitteedecision',
            name='berkas_lengkap',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatacommitteedecision',
            name='hasil_tinjauan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatacommitteedecision',
            name='nama_panitia',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatacommitteedecision',
            name='registration_data',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hasil_seleksi', to='hiring.registrationdata'),
        ),
        migrations.AlterField(
            model_name='registrationdatacommitteedecision',
            name='status_lulus',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatacommitteedecision',
            name='tanggal_tinjau',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='harapan_kontribusi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='minat_bakat',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='nama_formasi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='pengalaman',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatadivisionchoice',
            name='tingkat_jabatan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='keterangan_tambahan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='lembaga_penyelenggara',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='masa_kerja_akhir',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='masa_kerja_mulai',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataexperience',
            name='nama_kegiatan',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='bahasa',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='keterampilan_bicara',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='keterampilan_membaca',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='keterampilan_menulis',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='skor_kemahiran',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatalanguage',
            name='tahun_tes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataorganization',
            name='deskripsi_jabatan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataorganization',
            name='masa_jabatan_akhir',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataorganization',
            name='masa_jabatan_mulai',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataorganization',
            name='nama_institusi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataorganization',
            name='posisi_jabatan',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='deskripsi_tambahan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='jenis_publikasi',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='judul_publikasi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='lembaga_publikasi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatapublication',
            name='tahun_publikasi',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='jenjang',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='lembaga_penyelenggara',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='nama_beasiswa',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='tahun_beasiswa',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdatascholarship',
            name='tipe_pendanaan',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataskill',
            name='saintek',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataskill',
            name='sastra',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataskill',
            name='seni',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdataskill',
            name='sosial',
            field=models.TextField(blank=True, null=True),
        ),
    ]
