# Generated by Django 4.1.7 on 2023-07-14 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiring', '0004_alter_registrationdata_ekstrakurikuler_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationdata',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tanggal_lahir',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tautan_dokumen',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='registrationdata',
            name='tautan_dokumen_drive_ppsn',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
